name: Feature Request
description: Propose a feature with use-case and acceptance criteria
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user problem are you trying to solve?
      placeholder: Clear pain point and context
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: What should the app do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: Other approaches you considered
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
      render: markdown
    validations:
      required: true
